# Generated by Django 5.1.6 on 2025-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_customuser_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bed_number',
            field=models.CharField(default=100, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='residential_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
