# Generated by Django 5.1.6 on 2025-03-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_customuser_bed_number_customuser_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_phone',
        ),
    ]
