# Generated by Django 5.1.6 on 2025-03-12 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_room_remove_userroom_room_id_userroom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
