# Generated by Django 5.1.6 on 2025-03-12 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_userroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestbox',
            name='requested_bed',
        ),
        migrations.RemoveField(
            model_name='requestbox',
            name='requested_room',
        ),
        migrations.AddField(
            model_name='requestbox',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requestbox',
            name='request_text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
