# Generated by Django 5.1.6 on 2025-03-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_feedback_date_alter_userroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='dates',
        ),
    ]
