# Generated by Django 5.1.6 on 2025-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_rename_date_feedback_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='dates',
            new_name='date',
        ),
    ]
