# Generated by Django 5.1.6 on 2025-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
