# Generated by Django 5.1.6 on 2025-03-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_remove_room_bed_number_remove_room_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsecurity',
            name='user',
        ),
        migrations.AddField(
            model_name='adminsecurity',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminsecurity',
            name='security_key',
            field=models.CharField(default='secretpassword', max_length=100),
        ),
    ]
