# Generated by Django 5.1.6 on 2025-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_setup_admin_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
