# Generated by Django 5.1.6 on 2025-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_feedback_breakfast_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='breakfast_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='dinner_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lunch_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
